// <auto-generated />
using System;
using Capstonep2.Infrastructure.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capstonep2.Migrations
{
    [DbContext(typeof(DefaultDBContext))]
    partial class DefaultDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Appointment", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("PDescription")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PatientID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Visit")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.ApptFinding", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FindingId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("FindingId");

                    b.ToTable("ApptFindings");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.ApptPrecription", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("ApptPrecriptions");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.ApptPurpose", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AppointmentID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AppointmetId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PurposeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentID");

                    b.HasIndex("PurposeId");

                    b.ToTable("ApptPurposes");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.ApptSymptom", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SymptomId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("SymptomId");

                    b.ToTable("ApptSymptoms");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.ConsultationRecord", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AppointmentID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PatientID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("AppointmentID");

                    b.HasIndex("PatientID");

                    b.ToTable("ConsultationRecords");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Finding", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AppointmentID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ConsultationRecordID")
                        .HasColumnType("char(36)");

                    b.Property<string>("FName")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("AppointmentID");

                    b.HasIndex("ConsultationRecordID");

                    b.ToTable("Findings");

                    b.HasData(
                        new
                        {
                            ID = new Guid("efd1381a-4c3d-4260-aaf2-04a0a26591bc"),
                            FName = "age-related macular degeneration"
                        },
                        new
                        {
                            ID = new Guid("672a4093-269e-47aa-879c-738cf2bf5e55"),
                            FName = "cataract"
                        },
                        new
                        {
                            ID = new Guid("332d1fb4-35f1-48d8-ac19-f66472fce607"),
                            FName = "diabetic"
                        },
                        new
                        {
                            ID = new Guid("629d1da5-bf42-4dd5-9eda-614ba1260f03"),
                            FName = "retinopathy"
                        },
                        new
                        {
                            ID = new Guid("ab7f6ecf-7e82-4281-b90d-69f4ef72b66a"),
                            FName = "glaucoma"
                        });
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Patient", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            ID = new Guid("2b792220-f333-49ec-abe2-3a6fc4edb0c2"),
                            Address = "Luakan,Dinalupihan, Bataan",
                            BirthDate = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Luisa Katrina",
                            Gender = 0,
                            LastName = "Reyes",
                            MiddleName = "Pangilinan"
                        },
                        new
                        {
                            ID = new Guid("5a7e7bc3-8816-41df-b44d-eeb60ae99b5b"),
                            Address = "Luakan,Dinalupihan, Bataan",
                            BirthDate = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Clarissa Joy",
                            Gender = 0,
                            LastName = "Flores",
                            MiddleName = "Gozon"
                        },
                        new
                        {
                            ID = new Guid("8664a4bd-0ec6-4aaa-83e6-7d2bd0315b5a"),
                            Address = "Bacong,Hermosa, Bataan",
                            BirthDate = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Raniel",
                            Gender = 1,
                            LastName = "David",
                            MiddleName = "Mallari"
                        });
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Prescription", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AppointmentID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ConsultationRecordID")
                        .HasColumnType("char(36)");

                    b.Property<string>("GName")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("AppointmentID");

                    b.HasIndex("ConsultationRecordID");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            ID = new Guid("3d588288-29d3-4f29-a6e4-45734f748986"),
                            GName = "Azelastine eye drops for allergies (Optilast)"
                        },
                        new
                        {
                            ID = new Guid("71bd251b-43a1-4f19-a750-fc04e5e74876"),
                            GName = "Atropine eye drops (Minims Atropine)"
                        },
                        new
                        {
                            ID = new Guid("974e4796-cbb3-4bd8-b0a5-f5886cb10d45"),
                            GName = "Apraclonidine eye drops (Iopidine)"
                        },
                        new
                        {
                            ID = new Guid("35538073-8775-4efd-ab8a-c37479dc5109"),
                            GName = "Antazoline and xylometazoline eye drops (Otrivine-Antistin)"
                        },
                        new
                        {
                            ID = new Guid("cf144c28-7bca-4140-91bd-57983d308c1c"),
                            GName = "Aciclovir eye ointment."
                        },
                        new
                        {
                            ID = new Guid("744fa268-a8fd-4d38-a7af-239354d507b4"),
                            GName = "Acetylcysteine for dry eyes (Ilube)"
                        });
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Purpose", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AppointmentID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentID");

                    b.ToTable("Purposes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f28dca4-e0f4-4798-a823-f44cdcd2a3b0"),
                            Name = " CheckUp"
                        },
                        new
                        {
                            Id = new Guid("70b4d9b7-e5bf-4da4-a355-a0af2da1d587"),
                            Name = "FollowUp"
                        },
                        new
                        {
                            Id = new Guid("912f8c3e-3ca7-4703-a858-2b9bc7612096"),
                            Name = "EyeGradeCheck"
                        },
                        new
                        {
                            Id = new Guid("3042ec44-a9b3-4bee-8a3d-14fd9f5167f7"),
                            Name = "Brokeneyeglasses"
                        },
                        new
                        {
                            Id = new Guid("9f87d3db-3842-4a4d-8552-b568c7f44620"),
                            Name = "Surgery"
                        });
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Role", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = new Guid("2afa881f-e519-4e67-a841-e4a2630e8a2a"),
                            Abbreviation = "Pt",
                            Description = "One who receives medical treatment",
                            Name = "patient"
                        },
                        new
                        {
                            ID = new Guid("54f00f70-72b8-4d34-a953-83321ff6b101"),
                            Abbreviation = "Adm",
                            Description = "One who manages the system",
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Symptom", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AppointmentID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentID");

                    b.ToTable("Symptoms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32d18f17-4f8f-4534-9394-703261e2390b"),
                            Name = "Blurred, clouded or dim vision."
                        },
                        new
                        {
                            Id = new Guid("10cbac3c-2dbf-45c9-8832-e6d2dd0b2168"),
                            Name = "Problem seeing at night."
                        },
                        new
                        {
                            Id = new Guid("0bd555b4-5d90-4033-abd7-2b19dfce9f41"),
                            Name = "Problem seeing through light and glare"
                        },
                        new
                        {
                            Id = new Guid("e0d9efd5-c988-4692-aafd-c0096b0093ff"),
                            Name = "Seeing 'halos' around lights."
                        },
                        new
                        {
                            Id = new Guid("8f908b6a-618f-486f-9aa3-ecac26ddd539"),
                            Name = "Frequently changing contact lens"
                        },
                        new
                        {
                            Id = new Guid("6e880219-f4fa-4743-bcfd-295fcd602ce3"),
                            Name = "Prescription or eyeglasses"
                        },
                        new
                        {
                            Id = new Guid("b7862274-66a6-4ed1-a193-d1f014fe5ff9"),
                            Name = "Faded view of colors"
                        },
                        new
                        {
                            Id = new Guid("03e03141-ccd4-4d5c-a7d5-2c739c4e8c2a"),
                            Name = "Faded view of colors"
                        },
                        new
                        {
                            Id = new Guid("89fa12ed-89c5-4535-ae64-7544221ac48e"),
                            Name = "Cataracts"
                        },
                        new
                        {
                            Id = new Guid("b7892990-94dd-44b8-a7cb-d142cd10e3d8"),
                            Name = "Dry Eyes"
                        },
                        new
                        {
                            Id = new Guid("b9e8ceda-2511-4f71-9c57-70bf77e128a0"),
                            Name = " Eye Pain"
                        },
                        new
                        {
                            Id = new Guid("cd2345d7-aba2-4228-9303-b647f6d70574"),
                            Name = "excessive tearing"
                        },
                        new
                        {
                            Id = new Guid("dac8c2aa-2a57-40ef-ae4c-9316a3e27d1a"),
                            Name = "burning"
                        },
                        new
                        {
                            Id = new Guid("4807111d-782b-4099-b24a-9d50cdb1093f"),
                            Name = "swollen"
                        },
                        new
                        {
                            Id = new Guid("1b89eb12-b4ae-4a4e-af4a-68a8d5f9f998"),
                            Name = "greasy or drooping eyelids"
                        });
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.User", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PatientID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RoleID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("0352c124-f290-4f99-b1a5-e235cafcd836"),
                            Address = "Dinalupihan, Orani, Bataan",
                            BirthDate = new DateTime(2001, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "luisa@yahoo.com",
                            FirstName = "Luisa Katrina",
                            Gender = 0,
                            LastName = "Pangilinan",
                            MiddleName = "Reyes",
                            PatientID = new Guid("2b792220-f333-49ec-abe2-3a6fc4edb0c2"),
                            RoleID = new Guid("2afa881f-e519-4e67-a841-e4a2630e8a2a")
                        },
                        new
                        {
                            ID = new Guid("d7dbd16f-1c71-4415-a147-22a2b428bf95"),
                            Address = "Dinalupihan, Orani, Bataan",
                            BirthDate = new DateTime(2001, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joy@yahoo.com",
                            FirstName = "Clarissa Joy",
                            Gender = 1,
                            LastName = "Gozon",
                            MiddleName = "Flores",
                            PatientID = new Guid("5a7e7bc3-8816-41df-b44d-eeb60ae99b5b"),
                            RoleID = new Guid("2afa881f-e519-4e67-a841-e4a2630e8a2a")
                        },
                        new
                        {
                            ID = new Guid("7e5e4f74-9902-43da-9974-4b2a08814398"),
                            Address = "Dinalupihan, Orani, Bataan",
                            BirthDate = new DateTime(2001, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "renieldavid@yahoo.com",
                            FirstName = "Reniel",
                            Gender = 1,
                            LastName = "Mallari",
                            MiddleName = "David",
                            PatientID = new Guid("8664a4bd-0ec6-4aaa-83e6-7d2bd0315b5a"),
                            RoleID = new Guid("2afa881f-e519-4e67-a841-e4a2630e8a2a")
                        },
                        new
                        {
                            ID = new Guid("1bd5f519-b891-4491-9a7c-a86cd0c2a15e"),
                            Address = "Dinalupihan, Orani , Bataan",
                            BirthDate = new DateTime(2002, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@yahoo.com",
                            FirstName = "admin",
                            Gender = 0,
                            LastName = "admin",
                            MiddleName = "admin",
                            RoleID = new Guid("54f00f70-72b8-4d34-a953-83321ff6b101")
                        },
                        new
                        {
                            ID = new Guid("00acfb7f-6c90-459a-b53f-bf73ddac85b4"),
                            Address = "Dinalupihan, Orani , Bataan",
                            BirthDate = new DateTime(2002, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Janedavid@yahoo.com",
                            FirstName = "Jane",
                            Gender = 0,
                            LastName = "David",
                            MiddleName = "Adan",
                            RoleID = new Guid("54f00f70-72b8-4d34-a953-83321ff6b101")
                        });
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.UserLogin", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("UserLogins");

                    b.HasData(
                        new
                        {
                            ID = new Guid("6d106ed8-59b7-4a98-baeb-e8fc23c10f18"),
                            Key = "Password",
                            Type = "General",
                            UserID = new Guid("0352c124-f290-4f99-b1a5-e235cafcd836"),
                            Value = "$2a$11$eHSuQYWLkuTA8IRxxt.cduhy0r6lWhbvg85fDHOnjlWBg6BzYMeO."
                        },
                        new
                        {
                            ID = new Guid("93baf46a-dab2-49b9-b49e-445363f55632"),
                            Key = "IsActive",
                            Type = "General",
                            UserID = new Guid("0352c124-f290-4f99-b1a5-e235cafcd836"),
                            Value = "true"
                        },
                        new
                        {
                            ID = new Guid("ce0ef5f4-8e17-4dcf-9202-5a90ff08cc4a"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserID = new Guid("0352c124-f290-4f99-b1a5-e235cafcd836"),
                            Value = "0"
                        },
                        new
                        {
                            ID = new Guid("cdf9f564-aaa4-4226-820f-819e69bd0779"),
                            Key = "Password",
                            Type = "General",
                            UserID = new Guid("d7dbd16f-1c71-4415-a147-22a2b428bf95"),
                            Value = "$2a$11$I.6j4QjM3ITqJUgLFBFw/OO.59XpPrydKJIQNN/tGCpyD8Mw5nMeu"
                        },
                        new
                        {
                            ID = new Guid("edcfedbe-8ca4-4820-b561-f12213c46d52"),
                            Key = "IsActive",
                            Type = "General",
                            UserID = new Guid("d7dbd16f-1c71-4415-a147-22a2b428bf95"),
                            Value = "true"
                        },
                        new
                        {
                            ID = new Guid("4b199242-5b91-48d0-a2cf-3425a5639e0d"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserID = new Guid("d7dbd16f-1c71-4415-a147-22a2b428bf95"),
                            Value = "0"
                        },
                        new
                        {
                            ID = new Guid("e8deb6f5-f170-4b91-ac4c-18a31c78d0f0"),
                            Key = "Password",
                            Type = "General",
                            UserID = new Guid("1bd5f519-b891-4491-9a7c-a86cd0c2a15e"),
                            Value = "$2a$11$RzuJmfq.Koasj4RpeOVl8eSnBPweLdbH47tyh/ulZOp4ms08Auf4O"
                        },
                        new
                        {
                            ID = new Guid("ac95e264-1de1-4e4f-b86f-00bdbbf198a3"),
                            Key = "IsActive",
                            Type = "General",
                            UserID = new Guid("1bd5f519-b891-4491-9a7c-a86cd0c2a15e"),
                            Value = "true"
                        },
                        new
                        {
                            ID = new Guid("ea6ce764-d2aa-469c-80f5-b0df4d781221"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserID = new Guid("1bd5f519-b891-4491-9a7c-a86cd0c2a15e"),
                            Value = "0"
                        },
                        new
                        {
                            ID = new Guid("754d6fef-c5b3-4893-be82-d386db72d021"),
                            Key = "Password",
                            Type = "General",
                            UserID = new Guid("00acfb7f-6c90-459a-b53f-bf73ddac85b4"),
                            Value = "$2a$11$a9I/7jOR/4reVn6D68ZnAu9cVx7fZ6QEmBHZxvglRnNd8UBxEiiu."
                        },
                        new
                        {
                            ID = new Guid("b2223936-bb8b-4df4-a725-3dee85d65ca7"),
                            Key = "IsActive",
                            Type = "General",
                            UserID = new Guid("00acfb7f-6c90-459a-b53f-bf73ddac85b4"),
                            Value = "true"
                        },
                        new
                        {
                            ID = new Guid("93dbf407-d9cc-4708-8c74-fa32b3375786"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserID = new Guid("00acfb7f-6c90-459a-b53f-bf73ddac85b4"),
                            Value = "0"
                        },
                        new
                        {
                            ID = new Guid("11d6b1e6-4f38-49dd-8d72-bfaac49e742b"),
                            Key = "Password",
                            Type = "General",
                            UserID = new Guid("7e5e4f74-9902-43da-9974-4b2a08814398"),
                            Value = "$2a$11$a2em.AzzWWzIKh6gzqwFZeukxknl0AtCE1.WdqTgeDS3okPTSaML6"
                        },
                        new
                        {
                            ID = new Guid("2a73ece9-2473-45a8-934a-1fad967be4f2"),
                            Key = "IsActive",
                            Type = "General",
                            UserID = new Guid("7e5e4f74-9902-43da-9974-4b2a08814398"),
                            Value = "true"
                        },
                        new
                        {
                            ID = new Guid("f1205ce1-ba86-41b0-a688-0b5cd05db839"),
                            Key = "LoginRetries",
                            Type = "General",
                            UserID = new Guid("7e5e4f74-9902-43da-9974-4b2a08814398"),
                            Value = "0"
                        });
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RoleID")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("341afcc4-ebdf-4403-ae6a-38d83d280c81"),
                            RoleID = new Guid("2afa881f-e519-4e67-a841-e4a2630e8a2a"),
                            UserID = new Guid("0352c124-f290-4f99-b1a5-e235cafcd836")
                        },
                        new
                        {
                            Id = new Guid("05f046a1-34a1-4792-bfae-5bdcde4db044"),
                            RoleID = new Guid("2afa881f-e519-4e67-a841-e4a2630e8a2a"),
                            UserID = new Guid("d7dbd16f-1c71-4415-a147-22a2b428bf95")
                        },
                        new
                        {
                            Id = new Guid("993bb3fe-3735-44a5-a497-f62b4601d1b6"),
                            RoleID = new Guid("54f00f70-72b8-4d34-a953-83321ff6b101"),
                            UserID = new Guid("1bd5f519-b891-4491-9a7c-a86cd0c2a15e")
                        },
                        new
                        {
                            Id = new Guid("7a109e76-06f6-4deb-bd12-e999816b2181"),
                            RoleID = new Guid("54f00f70-72b8-4d34-a953-83321ff6b101"),
                            UserID = new Guid("00acfb7f-6c90-459a-b53f-bf73ddac85b4")
                        },
                        new
                        {
                            Id = new Guid("af51f51a-6037-4881-afa5-e26af433b68a"),
                            RoleID = new Guid("2afa881f-e519-4e67-a841-e4a2630e8a2a"),
                            UserID = new Guid("7e5e4f74-9902-43da-9974-4b2a08814398")
                        });
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Appointment", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.ApptFinding", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Finding", "Finding")
                        .WithMany()
                        .HasForeignKey("FindingId");

                    b.Navigation("Appointment");

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.ApptPrecription", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionId");

                    b.Navigation("Appointment");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.ApptPurpose", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentID");

                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Purpose", "Purpose")
                        .WithMany()
                        .HasForeignKey("PurposeId");

                    b.Navigation("Appointment");

                    b.Navigation("Purpose");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.ApptSymptom", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Symptom", "Symptom")
                        .WithMany()
                        .HasForeignKey("SymptomId");

                    b.Navigation("Appointment");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.ConsultationRecord", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentID");

                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID");

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Finding", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Appointment", null)
                        .WithMany("Findings")
                        .HasForeignKey("AppointmentID");

                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.ConsultationRecord", "Consultation")
                        .WithMany()
                        .HasForeignKey("ConsultationRecordID");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Prescription", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Appointment", null)
                        .WithMany("Prescriptions")
                        .HasForeignKey("AppointmentID");

                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.ConsultationRecord", "Consultation")
                        .WithMany()
                        .HasForeignKey("ConsultationRecordID");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Purpose", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Appointment", null)
                        .WithMany("Purposes")
                        .HasForeignKey("AppointmentID");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Symptom", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Appointment", null)
                        .WithMany("Symptoms")
                        .HasForeignKey("AppointmentID");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.User", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID");

                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.Navigation("Patient");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.UserRole", b =>
                {
                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.HasOne("Capstonep2.Infrastructure.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Capstonep2.Infrastructure.Domain.Models.Appointment", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Prescriptions");

                    b.Navigation("Purposes");

                    b.Navigation("Symptoms");
                });
#pragma warning restore 612, 618
        }
    }
}
